language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

matrix:
  allow_failures:
    - php: 7.0
  fast_finish: true

sudo: false

before_install:
  - composer self-update

install:
  - travis_retry composer update --prefer-stable

script: vendor/bin/phpunit